name: iglm
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.79
  - datasets=2.1.0
  - h5py=3.6.0
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pandas=1.4.2
  - pip=22.0.4
  - pyarrow=6.0.1
  - python=3.10.4
  - pytorch=1.11.0
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - seaborn=0.11.2
  - setuptools=62.1.0
  - tokenizers=0.10.3
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm=4.64.0
  - transformers=4.6.1
